### PR TITLE
Add custom arsenal cheatsheets feature for my resources

### PR DESCRIPTION
**Pull request by cHJlaXpoZXI**
# Description

This PR is a evolution of my resource function to add the possibility for Exegol users to have their own cheatsheets inside Arsenal.

If there are some cheatsheets inside cheatsheet folder in "my resources" a copy is done to /root/.cheats (valid path for arsenal). Else, the folder is created for future use.

Pretty basic feature but that can really enforce the customisation of Exegol. 

# Point of attention

I hope my PR is OK :)

### CODE REVIEW

**Comment by ShutdownRepo** [comment]
Thank you for this PR!
Two remarks:
2. Would it be possible to have the `.cheats` named `.arsenal_cheatsheet` instead?
3. Any modification to the "my-resources" part needs to be documented in [Exegol-docs](https://github.com/ThePorgs/Exegol-docs), in the `dev-images` branch, in the "supported setups" section (https://exegol.readthedocs.io/en/latest/exegol-image/my-resources.html#supported-setups)

Also, maybe you can contribute to Arsenal directly to add your own content 😉

**Review by ShutdownRepo — CHANGES_REQUESTED** [review]
Rename file + create the appropriate documentation PR in Exegol-docs as per prevous comment

**Comment by cHJlaXpoZXI** [comment]
> Thank you for this PR! Two remarks: 2. Would it be possible to have the `.cheats` named `.arsenal_cheatsheet` instead? 3. Any modification to the "my-resources" part needs to be documented in [Exegol-docs](https://github.com/ThePorgs/Exegol-docs), in the `dev-images` branch, in the "supported setups" section (https://exegol.readthedocs.io/en/latest/exegol-image/my-resources.html#supported-setups)
> 
> Also, maybe you can contribute to Arsenal directly to add your own content 😉

I answer for each remarks : 

1 - I can rename it but I need to modify the code in Arsenal. This is the config file for cheatsheet path : 

```python

# Base paths
DATAPATH = join(dirname(dirname(abspath(__file__))), 'data')
BASEPATH = dirname(dirname(dirname(abspath(__file__))))
HOMEPATH = expanduser("~")
FORMATS = ["md", "rst", "yml"]
EXCLUDE_LIST = ["README.md", "README.rst", "index.rst"]
FUZZING_DIRS = ["/usr/local/share/wordlists/**/*.txt"]

CHEATS_PATHS = [
    join(DATAPATH, "cheats"),  # DEFAULT
    # Additional paths below, add comma to line above
    join(BASEPATH, "my_cheats"),
    join(HOMEPATH, ".cheats")
 ```
I tried to have the absolute path of my_cheat folder but I cannot find it and the folder doesn't seems to exist either (maybe pipx installation). The bash script is executed every time a container is created ? The only downside is if Arsenal is modified, it's can be an issue.

2 - I will make a PR for the doc ASAP.

3 - Arsenal seems not to be really community driven tbh. And I think, you can have the perfect workflow for a team : 

-> Github with all cheatsheets
-> git clone the project in the my resource folder in Exegol
-> You have it in every container
-> You add a command or a cheatsheet -> git commit.

I think it's a good way to manage team's cheatsheet (it's my vision, maybe I get wrong ^^)

**Comment by ShutdownRepo** [comment]
Maybe we should switch to a source install to be able to have the cheats file inside the folder itself 🤷 
Agree with the rest

**Comment by cHJlaXpoZXI** [comment]
So I talk with Mayfly about this feature and the issue I have with Arsenal code (arsenal call a bash script which call a python exec).

From source in a venv, this is impossible to isolate (I don't find a way to do that tbh).

Mayfly have added my-resources/my-cheats folder directly in arsenal.

Now the function just check if the folder my-cheat exist if not it create it.

If this is good for you, I will push the PR for the doc and we are good to go for this feature ;)

**Comment by ShutdownRepo** [comment]
Awesome 😍 
One small change though @cHJlaXpoZXI @mayfly277, do you mind changing `my-resources/my-cheats` to `my-resources/arsenal-cheats`?

**Review by ShutdownRepo — CHANGES_REQUESTED** [review]
Changing the dir name would be perfect 🙏

**Comment by ShutdownRepo** [comment]
Merged https://github.com/ThePorgs/Exegol-docs/pull/58
Now merging this

**Pull request merged**
